# Generated by Django 4.1 on 2022-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_worker_application_username_worker_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
