# Generated by Django 4.1 on 2022-11-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_worker_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='username',
            new_name='worker',
        ),
    ]
